services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    ports:
      - '8000:8000'
    volumes:
      - ./spare_parts.db:/app/spare_parts.db
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/health']
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    command: streamlit run frontend/app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - '8501:8501'
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      backend:
        condition: service_healthy

volumes:
  spare_parts_db: